name: After push
on:
  workflow_run:
    workflows: 
      - ci
    branches: 
      - main
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "this is a deploy run"
          echo "gitsha: $GITHUB_SHA"
