name: Test
on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "this is a test run"
          echo "gitsha: $GITHUB_SHA"
      - name: sleep
        run: sleep 1s
