name: Test
on:
  push:
    branches:
    - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        level: []
    steps:
      - name: echo
        run: |
          echo "this is a test run"
          echo "gitsha: $GITHUB_SHA"
          echo "git head ref: ${{ github.head_ref }}"
          echo "git ref: ${{ github.ref }}"
          echo "git ref name: ${{ github.ref_name }}"
      - name: sleep
        run: sleep 1s
